### ISSUE TITLE
Appveyor CI is failing

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1009]
Appveyor CI is current failing in all PRs with the following lines:

<img width="815" alt="Screen Shot 2020-01-20 at 12 42 20 PM" src="https://user-images.githubusercontent.com/32864116/72699196-6258de80-3b82-11ea-9446-4c13d110b8e6.png">
<img width="836" alt="Screen Shot 2020-01-20 at 12 42 42 PM" src="https://user-images.githubusercontent.com/32864116/72699198-6422a200-3b82-11ea-8566-055f8d3f36a7.png">

Link to one of the Appveyor build for PR #1005: https://ci.appveyor.com/project/eugenepeh/reposense/builds/30213033

**Comment by jamessspanggg** [comment]
May be due to AppVeyor's recent Windows image update: https://www.appveyor.com/updates/

**Comment by 0blivious** [comment]
I feel the failed test is actually the 2 below. However, I am unable to reproduce them locally.
![image](https://user-images.githubusercontent.com/39231750/72697952-fde75080-3b7c-11ea-8aea-e64700a595bc.png)
![image](https://user-images.githubusercontent.com/39231750/72697999-2ff8b280-3b7d-11ea-87e0-b8dd1456704c.png)

**Comment by fzdy1914** [comment]
@reposense/devs Please help with this issue and try to get it solved quickly.

**Comment by fzdy1914** [comment]
![image](https://user-images.githubusercontent.com/35621726/72701590-c67fa080-3b8a-11ea-9057-0cec4a576f03.png)

**Comment by jamessspanggg** [comment]
With the update, using `git checkout` to a branch with illegal window file names will incur an exception...

**Comment by jylee-git** [comment]
I actually think that these two test cases are no longer relevant and can be removed.

Reason: in windows, repos and branches that are to be analyzed would have been checked for illegal filenames via gitlstree (from the bare clone) before they are checked out from the bare repo to the actual ones

**Comment by jylee-git** [comment]
Investigating further, the test cases worked on Git 2.23 but not any versions beyond that.

Current version is 2.25 and that's the version that the AppVeyor is now on with the latest update

**Comment by 0blivious** [comment]
As updated from Git v2.24, Git for windows would print error for illegal file name and prevent it from adding into index. As in our test cases we run the command `git checkout someInvalidName`, an exception is expected to be thrown, and since we do not catch it, the test fail. An work around in local machine is to disable `core.protectNTFS`. 

The doc for `protectNTFS` can be found here. It is set to be true for windows and false for other systems. https://git-scm.com/docs/git-config

Since even the git command will fail on windows, maybe we should remove the 2 tests, or we test if the correct exception is to be thrown

**Comment by yong24s** [comment]
Let's remove the two outdated tests.

Well done in the prompt investigation and thank you for the effort 👍.
