### ISSUE TITLE
Fail to analyse repo

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1019]
After merge PR #969, Reposense fail to analyse repo that was once working before the commit. And Intellij report that is due to java.lang.ArrayIndexOutOfBoundsException at CommitInfoAnalyzer.

Arguments to reproduce `-Dargs="--repos https://github.com/CS2103-AY1819S2-W15-2/main.git --output output_path/ --since 21/10/2017 --until 21/11/2019 --view"`

![image](https://user-images.githubusercontent.com/39231750/72894149-a05a2c00-3d55-11ea-9068-1ef72294ec4b.png)

**Comment by jamessspanggg** [comment]
Did an investigation. Apparently the bug is due to commits that have no changes (i.e. empty commits with `git commit --allow-empty`).

With these commits, the `ref names` in GitLog will be empty. The regex then fails to split the git log result to also obtain the ref name, hence accessing the ref name index will incur an ArrayOutOfBoundsException.
