### ISSUE TITLE
Authorship panel: date range not reactive

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1041]
When changing date settings such as sinceDate and untilDate in Chart panel, the corresponding date range in Authorship page is not updated. The date range will not updated even after closing and reopen the tab. It will only change after we reload the page.

May be we should make it reactive. At least the date should be updated when we reopen the tab.

**Comment by 0blivious** [comment]
@fzdy1914 Can I ask your opinion on this?

**Comment by fzdy1914** [comment]
I got a similar question before. I don't think the data range of authorship will be updated even we reload the page. 

It is due to the inner design of splitting v_summary and v_authorship. Prof and other seniors believes that it is better to have separate controls for v_summary and v_authorship. 

However, it may be a feature in the future to support this. :)
