### ISSUE TITLE
Large number of repos not analyzed

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1054]
There was a large number of repos which were not analyzed. Let's try to understand why.

![Screen Shot 2020-02-04 at 7 01 05 PM](https://user-images.githubusercontent.com/35946746/73739194-bc5fc380-4780-11ea-9417-a140e8b8448a.png)

**Comment by anubh-v** [comment]
Do you have the configs / exact command used for this?

**Comment by damithc** [comment]
It's here https://github.com/nus-cs2103-AY1920S2/ip-dashboard
Seems previously it was using the release version. I changed it just now to use master branch instead.
Output is here https://nus-cs2103-ay1920s2.github.io/ip-dashboard/
Can check after some time to see if using the master branch fixed the problem.

**Comment by anubh-v** [comment]
I've taken a look at the current dashboard. There are 5 repos that cannot be analyzed.

Here is what I found so far (will update as I identify the issues)

- Repo: https://github.com/TheElectricBlender/duke.git
  There is a file which has a name following this pattern: `$FILE_NAME$`.
  When we perform `git blame`, this file name is interpreted as `$` and an exception is thrown since
  there isn't any file named `$`.
  This likely occurs because `$` symbol is used for parameter expansion in the shell.

**Comment by Tejas2805** [comment]
I have found out the issues for the rest. Have updated Prof

**Comment by Tejas2805** [comment]
Closing this issue as it seems to be solved. Thanks for the help @anubh-v
