### ISSUE TITLE
Colour repetition in breakdown by filetype

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1147]
When many file types are provided, colors begin to repeat themselves. 

![Screen Shot 2020-03-15 at 4 48 26 AM](https://user-images.githubusercontent.com/35946746/76690169-80215c00-6678-11ea-9c36-d275221642a9.png)

[Link to reproduce](https://nus-cs3281.github.io/2020-dashboard/#search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByAuthors&breakdown=true&since=2019-12-01&tabOpen=false)

**Comment by jamessspanggg** [comment]
Currently, the colours are chosen through a rotation of the predefined colour values. So if the number of filetype exceeds the number of predefined colours, they start to repeat.

I think we can either randomise the colour selection (which have low chances or having colours that repeat), or stick with the current implementation to add more predefined colours (perhaps we can make use of our mui-colours)?

**Comment by jamessspanggg** [comment]
The randomised colour selection may not be a good option as the discussion in #487 prefers colours with higher contrast against one another. So perhaps we can stick with our current implementation and utilise the `mui-colors` instead of the current predefined values.

**Comment by damithc** [comment]
It is fine to use randomized colors _after_ the standard selection of colors have been exhausted. There is a range of usage in which the software works optimally. Allowing to exceed that range is already a bonus (instead of limiting the number of categories, in this case); we don't have to provide an _optimal_ experience beyond that range.
