### ISSUE TITLE
Setup Github Actions for first time contributors

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1166]
First-time contributors have a difficult time matching RepoSense's contribution guidelines and it becomes the onus of the senior developers to manually check and guide them. Though this is a good practice, I think we should automate the first level of interaction. 

Suggestion: Setup Github Actions to reply to first-time developers whenever they open a new PR, to guide them related to the checks and commit message. Then, the senior developers can come in and guide. 

Benefits: The senior developers can focus more on guiding the contributor on their code rather than project management.

**Comment by Tejas2805** [comment]
@damithc Your opinion on this?

**Comment by damithc** [comment]
Sure. give it a try.
While we are are it, we can also automate other housekeeping tasks such as auto-closing inactive PRs?

**Comment by Tejas2805** [comment]
Surely. Will look into it.

**Comment by dcshzj** [comment]
> While we are are it, we can also automate other housekeeping tasks such as auto-closing inactive PRs?

This was done in #1299 and #1456.

> Suggestion: Setup Github Actions to reply to first-time developers whenever they open a new PR, to guide them related to the checks and commit message. Then, the senior developers can come in and guide.

Can I suggest instead of replying using GitHub Actions, we can use a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) which nudges the contributor to fill in the necessary details. Something similar to [the one done in MarkBind](https://github.com/MarkBind/markbind/blob/master/.github/PULL_REQUEST_TEMPLATE) should be sufficient for us.
