### ISSUE TITLE
RepoLocation: Redundant backslashes in regex used for parsing repo url

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1212]
Our current regex is:
https://github.com/reposense/RepoSense/blob/7fe12bf20b3a1a771f79c4dd808f5511fe9bfeba/src/main/java/reposense/model/RepoLocation.java#L17-L18

I believe we can simplify it to:
`^https?://github.com/(?<org>.+?)/(?<repoName>.+?)\.git$`

I.e. there is no need to escape the forward slash `/` character with the `\\` characters, as
the forward slash does not have a special meaning when used on its own.

Reference: https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html

**Comment by anubh-v** [comment]
@fzdy1914 @jylee-git may I confirm this with you?
Please let me know if I'm wrong

**Comment by jylee-git** [comment]
Yes I believe forward slashes without any escaping it should work. But please help to test and ensure that forward-slash without escaping works in Java.

**Comment by anubh-v** [comment]
Ok. This issue can be solved after PR #528, because that PR introduces tests that verify the correctness of the regex expressions

**Comment by fzdy1914** [comment]
OK

**Comment by dcshzj** [comment]
I think this task is still relevant and the fix is relatively trivial, which is suitable for first timers. The proposed fixed is in the issue description.

However, there is a lack of tests in this area and should be added (as `RepoLocationTest`). Some of the tests in #1098 can be used to test for valid and invalid locations. This is to also verify that the new regex is correct.

**Comment by aidoxe-123** [comment]
Hi, I am wondering if it is OK for me to work on this issue as a first-timer?

**Comment by dcshzj** [comment]
@aidoxe-123 Please go ahead! Let us know if you require any assistance. :)
