### ISSUE TITLE
Author display name changes as sort within group changes

### ISSUE THREAD

**Issue by niqiukun** [reposense/RepoSense#1229]
Discovered in https://github.com/reposense/RepoSense/pull/1223

The author's display name should stay consistent on summary view when grouped by author, but currently it changes as the sorting within the group changes, since it takes the display name of the first repo sorted within the group.

Can be reproduced at https://reposense.netlify.com/. Choose group by author and change sort within groups. The author's displayed name changes and as a result the overall sorting changes as well.

**Comment by 0blivious** [comment]
The problem is the author did have 2 different display name and we can't judge which display name we want to use. Now we use the first display name after sorting. Maybe we should use name instead of display name if sort by author?

**Comment by HCY123902** [comment]
Hello, is this issue still active? I also think that it may be suitable to only use the author name when grouped by author.

**Comment by 0blivious** [comment]
This is one solution, but it is kinda misaligned with the purpose of using the display name. We might possibly want to have some UI like authorname (display name 1, display name 2)?

@fzdy1914 @damithc

**Comment by damithc** [comment]
Can provide an example to understand the problem? :-p

**Comment by HCY123902** [comment]
According to my understanding, the problem happens when the report is grouped by author, and when the category used to sort within group changes, the display name of each of the author changes, and as a result the sorting order between different group also changes.

![image](https://user-images.githubusercontent.com/54735123/109754522-24503a00-7c1f-11eb-9e8b-75884a0ec0b9.png)

This is the state when individual repository within a group is sorted according to repository title in ascending order.

![image](https://user-images.githubusercontent.com/54735123/109754757-94f75680-7c1f-11eb-88a7-7d9f133e566c.png)

When the sorting is according to repository title in descending order, the author display name is changed and its position in the summary view is also changed as a result.

**Comment by damithc** [comment]
Thanks for the explanation @HCY123902 
Perhaps we should choose the author name based on some algorithm so that we always end up choosing the same name no matter what's the sorting order is. .e.g., we choose the longest name
What do you think?

**Comment by HCY123902** [comment]
Yeah I agree. However, it is also possible that 2 display name can be of the same length. Will it be suitable to choose the name according to the alphabetical order instead?

**Comment by damithc** [comment]
> Yeah I agree. However, it is also possible that 2 display name can be of the same length. Will it be suitable to choose the name according to the alphabetical order instead?

Yes.

**Comment by gerhean** [comment]
Actually why not use the github name which seems to be consistent?
