### ISSUE TITLE
Missing radio button option to filter by filetype

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#1271]
The option to filter by filetype is missing (see below for a snapshot).

![image](https://user-images.githubusercontent.com/35756209/82726994-3a3ce000-9d1a-11ea-91a7-65cfa8c36a3a.png)

**Comment by damithc** [comment]
Oops. Good catch @jylee-git 
As this is an important feature, might not want to wait till a first timer fix it.

**Comment by niqiukun** [comment]
But as a user I would be quite confused by the use of radio button here. Because selecting all would mean no filtering and selecting individual types would enable the filter, the only purpose of the radio button is to choose between filter by glob and filter by file type. But maybe both filters can be applied?

**Comment by damithc** [comment]
> But as a user I would be quite confused by the use of radio button here. Because selecting all would mean no filtering and selecting individual types would enable the filter, the only purpose of the radio button is to choose between filter by glob and filter by file type. But maybe both filters can be applied?

Good point @niqiukun . There is some merit in using the filter value itself to determine if the user intends to apply that filter. That also means to 'not apply' a glob filter, the user has to clear the glob box. What if the user wants to alternate between the two for some reason e.g., apply the glob filter -> check for something -> apply the files filter -> check for something -> go back to the glob filter ...
That kind of behavior is easier when there is explicit enabling/disabling of the mode.

Do we want to let users apply both at the same time? There may be use cases for that too but that's a separate feature. If we go for that, we can use checkboxes instead of radio buttons?

**Comment by niqiukun** [comment]
> That kind of behavior is easier when there is explicit enabling/disabling of the mode.

I see. 

It turns out to be a small css glitch that can be fixed easily. If there is really a need to apply both filters we can have a separate issue for that. But maybe on hold for now.

**Comment by damithc** [comment]
> It turns out to be a small css glitch that can be fixed easily. If there is really a need to apply both filters we can have a separate issue for that. But maybe on hold for now.

Yes, the two things can be done as separate PRs.
