### ISSUE TITLE
Remaining erros in documentation

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1293]
Few observations and nits:

1) This should be `report`

![Screen Shot 2020-06-20 at 2 10 39 PM](https://user-images.githubusercontent.com/35946746/85194632-989cb480-b300-11ea-809c-083017605fa1.png)

2) This should be `Commits panel`

![Screen Shot 2020-06-20 at 2 11 31 PM](https://user-images.githubusercontent.com/35946746/85194664-af430b80-b300-11ea-920d-233361e93d1e.png)

3) Let's make it consistent by following the `Step 1` method in `RepoSense with Netlify`

![Screen Shot 2020-06-22 at 9 25 48 AM](https://user-images.githubusercontent.com/35946746/85240720-ad498b80-b46b-11ea-8313-929776c07838.png)

---

![Screen Shot 2020-06-22 at 9 26 02 AM](https://user-images.githubusercontent.com/35946746/85240725-b175a900-b46b-11ea-8ce4-689af4fe00c8.png)

**Comment by damithc** [comment]
For 3, the `step` style makes the code more complicated and used only where the normal numbered lists cannot be used due to some steps needing embedded content (which breaks list auto numbering). I don't think there is a lot to gain by using the `step` style everywhere. That is, we can consistently use two style: one for normal cases and one for more complicated cases.

**Comment by lm5lm5** [comment]
I have made the correction for the first 2 errors and created a PR.
