### ISSUE TITLE
Provide a way to go to the code view directly

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1327]
Consider a link like [this one](https://nus-cs2103-ay2021s1.github.io/ip-dashboard/#sort=groupTitle&groupSelect=groupByAuthors&search=daongochieu2810&sortWithin=title&timeframe=commit&mergegroup=false&breakdown=false&tabOpen=true&tabType=authorship&since=2020-08-14&tabAuthor=daongochieu2810&tabRepo=daongochieu2810%2Fip%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=java~md~fxml~sh~bat~gradle~txt) 
It's useful if the code is loaded automatically so that someone can use the link to point to their code e.g., to cite in the resume

My first thought is to somehow encode a flag into the URL, the same way we encode other info into the URL

**Comment by jamessspanggg** [comment]
@damithc do u mean allow to use a link to automatically load the code specific for a file? 

Currently we allow the code to load automatically when shared the link, but it will only remember the checked file types. i.e.  like this [link](https://dashboard-1335-pr-reposense-reposense.surge.sh/#search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=tests~docs~other)

**Comment by damithc** [comment]
> Currently we allow the code to load automatically when shared the link, but it will only remember the checked file types. i.e. like this [link](https://dashboard-1335-pr-reposense-reposense.surge.sh/#search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=tests~docs~other)

That's the type of link I meant but how does one get such a link?
My steps:
1. Click on the `</>` icon --> full code appears on the code panel
2. Copy the link from the Browser

But the link copied that way does not load the code automatically when someone else use it.

**Comment by jamessspanggg** [comment]
> But the link copied that way does not load the code automatically when someone else use it.

Hmm, using the same steps u listed, if you use this [link](https://dashboard-1335-pr-reposense-reposense.surge.sh/#search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=tests~docs~other) here it should automatically load the code right?

**Comment by damithc** [comment]
yes, it seems to work for that dashboard.
But can't seem to be able to do it with this one https://nus-cs2103-ay2021s1.github.io/ip-dashboard
It's using a very recent master branch (about a week old).

**Comment by jamessspanggg** [comment]
Ahh, It is fixed by a PR [here](https://github.com/reposense/RepoSense/pull/1332) merged two days ago.

**Comment by damithc** [comment]
> Ahh, It is fixed by a PR [here](https://github.com/reposense/RepoSense/pull/1332) merged two days ago.

Got it :-p Thanks for the troubleshooting @jamessspanggg 
Should be fine them. Closing.
