### ISSUE TITLE
Find an alternative to TravisCI

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1358]
TravisCI has [announced changes to its pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) which will limit free and open source projects to a fixed amount of credits (currently 10,000), unless a higher and renewable limit is requested. We will be affected when we are forced to migrate to `travis-ci.com` at the end of the year.

We might have to look for an alternative for our CI needs, or request from Travis Support for a reasonable renewable limit per month.

**Comment by damithc** [comment]
Thanks for bringing this up @dcshzj 
We should explore moving to GitHub Actions.

**Comment by Tejas2805** [comment]
Actually I explored a bit of this on my FYP. 

1) GitHub Actions will give us 2000 build mins per month. But they charge 10x times the rate for macOS and 2x times the rate for Windows. So, building for one actual minute on Mac will actually cost us 10 minutes of actual build time.
2) Travis is actually 1000 Linux build minutes in total. As 1000 actual Linux build minutes make it 10,000 credits. The rate charged for Windows (20x) and Mac (50x) is way more. 

Since we test on all three platforms:
1)  I think we should not move to Github Actions but rather use both the tools for building on different platforms. 
2) Or we can remove the building on Mac as it costs the most across all tools. CircleCI doesn't even provide Mac in their free package. But don't think removing Mac is a feasible solution.

**Comment by dcshzj** [comment]
> 1. GitHub Actions will give us 2000 build mins per month. But they charge 10x times the rate for macOS and 2x times the rate for Windows. So, building for one actual minute on Mac will actually cost us 10 minutes of actual build time.

I think the 2000 build minutes per month is for private repositories. It looks like GitHub Actions is completely free (no limits) for public repositories, they only impose a [usage limit to prevent abuse](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#usage-limits).

**Comment by Tejas2805** [comment]
> I think the 2000 build minutes per month is for private repositories. It looks like GitHub Actions is completely free (no limits) for public repositories, they only impose a [usage limit to prevent abuse](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#usage-limits).

Ya, realiised. I kind of misinterpreted that we will fall under the organisation criteria.
