### ISSUE TITLE
Console error when doing individual merge group

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1539]
**Tell us about your environment**

https://dashboard-1530-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false

**Please include the steps to reproduce the bug.**

1. Open console
2. Click this:
![image](https://user-images.githubusercontent.com/16630400/114263352-874fa080-9a17-11eb-9f6f-ec13f7418239.png)

**What was expected to happen?**
No console error.

**What actually happened? Please include a screenshot of the output.**
Console error.
UI wise everything seems ok.

**Comment by yhtMinceraft1010X** [comment]
I tried looking at this and noticed that it's due to the slice.repoId being passed in at the getLink() function in [v-ramp.vue](https://github.com/reposense/RepoSense/blob/master/frontend/src/components/v-ramp.vue) which may not have been recognised. 

<img width="902" alt="Screenshot (17)" src="https://user-images.githubusercontent.com/69678785/149609777-694a74b9-abea-4d32-84fc-c5dbb1110339.png">

Hence, the console error is thrown in [api.js](https://github.com/reposense/RepoSense/blob/master/frontend/src/utils/api.js).

Example of a line that does not appear to work with slice.repoId
```
window.REPOS[slice.repoId].location.organization
```

I intend to fix this by using the user.repoId for the getLink() function instead since the user.repoId is kept even for merged groups.
