### ISSUE TITLE
ConfigSystemTest run shallow-cloning test as normal cloning

### ISSUE THREAD

**Issue by aidoxe-123** [reposense/RepoSense#1579]
**Steps to reproduce:**

1. Run ConfigSystemTest.testSinceBeginningDateRangeWithShallowCloning()

**Expected:**
The repoConfigs created in ConfigSystemTest.generateReport will have isShallowCloningPerformed = true

**Actually:**
The repoConfigs created in ConfigSystemTest.generateReport will have isShallowCloningPerformed = false

![image](https://user-images.githubusercontent.com/58925632/128474055-2fff1864-4d98-4f38-98ab-d4cb57b781ed.png)

**Comment by yhtMinceraft1010X** [comment]
I did some debugging and I believe that for each repoConfig, the isShallowCloningPerformed boolean is taken from the relevant entry in the repo-config.csv file:
![image](https://user-images.githubusercontent.com/69678785/128591569-9e79effe-63d2-4fc3-a4a9-004ae4e1b7d3.png)

Because the shallow cloning field is blank, isShallowCloningPerformed is set to false:
![image](https://user-images.githubusercontent.com/69678785/128591635-7ff1425d-18e2-403d-8857-92837bbe56a1.png)

Not sure how to proceed from here since I'm not sure if the repo-config.csv values are intended to be kept as such.

**Comment by aidoxe-123** [comment]
I will try to fix this in #1570
