### ISSUE TITLE
Remove building of frontend when running backend tests

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1630]
**What feature(s) would you like to see in RepoSense?**

Currently, when running `gradlew test` or `gradlew test systemtest`, the frontend is built even though running the backend tests do not appear to require frontend in any way. 

I propose restructuring the dependencies in `build.gradle` such the frontend is not built when running `test` or `systemtest` alone. (I.e. not part of build)

**Comment by gerhean** [comment]
@dcshzj I have copied my comments over from #1631

Is it possible to just remove zipReport since it is just zipping an empty folder if buildFrontend is not run? Or is the real problem that buildFrontend needs to be run at least once, but the current script runs it multiple times which is redundant (Which means your code will cause unexpected bugs by not requiring buildFrontend)?

Actually the entire process is a little weird and should probably be overhauled. Maybe introduce a build everything command, and maybe add checks that the required components exist for each command else build them.

For example, startServerInBackground has some weird dependency issues.

**Comment by gerhean** [comment]
I propose for the gradle build to be overhauled, with the following functions:

- Build frontend only
- Build backend only
- Build both
- Build if not found in `\reposense-report`
- `startServerInBackground` which only depends on  "Build if not found in `\reposense-report`"

Existing to modify (?)
- Copy files from `\reposense-report` to frontend public folder should check that relevant files exist in `\reposense-report`?

**Comment by dcshzj** [comment]
@yhtMinceraft1010X Are you still working on this?

**Comment by yhtMinceraft1010X** [comment]
I'm putting it on hold for now. But I hope to revisit it after finishing up #1625

**Comment by yhtMinceraft1010X** [comment]
Will wait for the following before continuing on this:
- #1659 to be resolved since the backend currently uses `templateZip.zip` generated by building frontend. 
- A potential upgrade to Gradle 7.3 or [7.4](https://docs.gradle.org/current/release-notes.html), as mentioned in #1635.
