### ISSUE TITLE
Fix HighlightJS regression

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1633]
**Tell us about your environment**

* **RepoSense Version:** 
Master
* **OS and Version:**
* **Web Browser and Version (if applicable):**

Possible regression by #1412

**Please include the steps to reproduce the bug.**

Compare the authorship tab between a deployment from [Jan 2021](https://nus-cs2103-ay2021s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&since=2020-08-14&until=2020-09-27&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=AdithyaNarayan&tabRepo=AdithyaNarayan%2Fip%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=java~md~fxml~sh~bat~gradle~txt) and one from the current [master branch](https://reposense.netlify.app/?search=&tabOpen=true&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabType=authorship&authorshipIsMergeGroup=false&authorshipFileTypes=tests~docs~other~frontend~backend)

**What was expected to happen?**

Syntax highlighting.
![image](https://user-images.githubusercontent.com/16630400/151508435-97e4af54-f82b-4a23-8fb4-993c92837d1f.png)

**What actually happened? Please include a screenshot of the output.**
Import is not blue.
![image](https://user-images.githubusercontent.com/16630400/151508488-4a30a071-9616-427c-9b5f-8cc34ea9b500.png)

**Additional context**

If possible, consider upgrading to use https://github.com/highlightjs/vue-plugin

As far as I know, `/frontend/src/views/v-authorship.vue` is the only file which uses hljs.

[This](https://github.com/reposense/RepoSense/blob/c4d7690e7b2c3b2626187a2c26ee447d99adf15a/frontend/src/app.vue#L321) should also be replaced.

**Comment by damithc** [comment]
Upping the priority as this affects the usefulness of the code view.

**Comment by dcshzj** [comment]
@Zhou-Jiahao-1998 Are you able to prioritize this task as part of your ongoing efforts to upgrade to Vue 3?

**Comment by Zhou-Jiahao-1998** [comment]
@dcshzj I am looking into #1634 now. Once I clear up the extra import for highlight.js, it will be easier to upgrade it to the latest version. Does that sound ok?

**Comment by dcshzj** [comment]
Sure, sounds good. Thanks!

**Comment by Zhou-Jiahao-1998** [comment]
@dcshzj May I know if you know what exactly is the problem here? 

From what I see so far, the first screenshot is taken from the duke individual project. Since it is written from scratch, it makes sense to highlight every single line. The second screenshot is a team project, so some parts are not written by that particular user. 

When I looked into the Vue components, the segment (which is sub units of the file) is split by whether or not the lines are authored. If the unauthored segment is longer than 5 lines, it will be hidden by default.

I am not sure what is the buggy part about this feature. Could you elaborate a little more?

**Comment by damithc** [comment]
> I am not sure what is the buggy part about this feature. Could you elaborate a little more?

@Zhou-Jiahao-1998 although the plugin is called highlight.js, it is actually being used for syntax coloring, not highlighting lines. The problem is that we seem to have lost syntax coloring in the code view.

**Comment by dcshzj** [comment]
> When I looked into the Vue components, the segment (which is sub units of the file) is split by whether or not the lines are authored. If the unauthored segment is longer than 5 lines, it will be hidden by default.

You are correct about this. However, that's referring to the background highlighting, not the syntax highlighting. The background highlighting is working as intended (green for additions, red for deletions), but the issue is with the syntax highlighting (the color of the text itself).

> I am not sure what is the buggy part about this feature. Could you elaborate a little more?

The issue is that the HighlightJS library, which we use for syntax highlighting, is not working as intended. By intended, we are referring to each line in the code view using different colors as part of syntax highlighting. This [was working in a previous version of RepoSense before #1412](https://nus-cs2103-ay2021s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&since=2020-08-14&until=2020-09-27&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=AdithyaNarayan&tabRepo=AdithyaNarayan%2Fip%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=java~md~fxml~sh~bat~gradle~txt), but right now, all code is shown as black text, with no differentiating colors used for different parts of the code.

The syntax highlighting should always be done regardless of how much context the code has, because syntax highlighting is performed individually on each line without any consideration of where the code is in the codebase. HightlightJS does all that for us, so all we need is to make sure that it is properly loaded.

There are two parts of this issue:
1. HighlightJS is not currently being used correctly (which is the regression part). The intended outcome is that when a user uses the code view in the RepoSense report, the code has syntax highlight, and not just a block of black text.
2. The HighlightJS version used is an older one (which is the upgrading part). The intended outcome is that the HighlightJS library that we are using should use the latest version possible, so that we can take advantage of newer features that the library has to offer.

I believe that it should be possible to fix both of the issues above in one go, by using the solution proposed by @gerhean, although I am not entirely certain and will need a bit more investigation when implementing.

**Comment by Zhou-Jiahao-1998** [comment]
@damithc @dcshzj Alright I understand the problem now. Will fix it asap.

**Comment by Zhou-Jiahao-1998** [comment]
@dcshzj Can you take a look at my #1646 to see if this is the effect we want? For some reason, syntax highlighting is working after I upgrade to Vue 3.

**Comment by dcshzj** [comment]
@Zhou-Jiahao-1998 Yup, that looks correct to me. I am not too well versed with Vue but my hunch is that it has got something to do with the changes you made to `frontend/src/main.js`, as there is where the highlight.js library is loaded.
