### ISSUE TITLE
Update User Guide Java Version

### ISSUE THREAD

**Issue by Zhou-Jiahao-1998** [reposense/RepoSense#1635]
**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

The User Guide states Java 8 or later. However, I was unable to run RepoSense on Java 17.

**What would you like added or modified in the documentation?**

Update the User Guide to show the compatible Java versions accurately.

**Comment by dcshzj** [comment]
Are we able to make RepoSense work on Java 17?

**Comment by Zhou-Jiahao-1998** [comment]
@dcshzj I believe the reason why it did not work on Java 17 now is because we are currently using `Gradle 5.2.1`. According to the [Gradle User Manual](https://docs.gradle.org/current/userguide/compatibility.html), the first Gradle version that supports Java 17 is `7.3`. I think we will have to upgrade our Gradle version first. Maybe we can consider opening an issue regarding this?

**Comment by gerhean** [comment]
Does the new Gradle work with our currently supported Java versions?

**Comment by Zhou-Jiahao-1998** [comment]
@gerhean I think it does. You can find the list of Java versions [Enum JavaVersion](https://docs.gradle.org/current/javadoc/org/gradle/api/JavaVersion.html) and support since which Gradle version.

**Comment by yhtMinceraft1010X** [comment]
I think this issue concerns the developer guide rather than the user guide. I tested the `RepoSense.jar` for both the release version and the master branch (compiled using Java 8) with Java 17 runtime. The RepoSense.jar still works. 

![Screenshot (132)](https://user-images.githubusercontent.com/69678785/156100806-65dd7c40-5ef3-4da2-92e8-0ab336c2b50b.png)
Above is the command prompt showing that both versions of `RepoSense.jar` still work on Java 17 runtime. (The master branch version was built using `gradlew shadowJar` on Java 8.

![Screenshot (130)](https://user-images.githubusercontent.com/69678785/156100915-7fc7f613-bff0-40fa-8b09-380e89d7c6cb.png)
Above is a report for one of the versions of `RepoSense.jar`. The other version also works fine.

So the User Guide is still correct in saying that Java 8 or later works since the user is downloading a pre-compiled Java 8 jar file, which can still run on Java 17 runtime (provided that deprecated methods/variables etc are not used in the source code).

It is true that `Gradle 5.2.1` does not work with Java 17. In this case, the developer guide's `Setting up` page should be changed instead.
