### ISSUE TITLE
Windows CI on GitHub actions

### ISSUE THREAD

**Issue by gok99** [reposense/RepoSense#1723]
**What feature(s) would you like to see in RepoSense?**

Ubuntu and Mac CI is currently run on GitHub actions, while Windows CI is run on Appveyor. This is done to limit our reliance on a single CI provider. However, GitHub CI does make maintaining and monitoring CI much more convenient. Furthermore, when updates need to be made to CI scripts, it is easy to forget to also update Appveyor scripts.

As a compromise we might want to do Windows CI on GitHub actions as well. Changes made to GitHub actions scripts can be moved to Appveyor periodically/when necessary (this step can be non-trivial).

**Comment by damithc** [comment]
> This is done to limit our reliance on a single CI provider.

At the beginning, we were using Travis for Linux/Mac and AppVeyor for Windows because Travis didn't have Windows support. When Travis became less-friendly for free users, we moved from Travis to Github Actions. So, the split (at least the initial split) was accidental rather than intentional. I don't mind moving everything to GitHub actions.

**Comment by dcshzj** [comment]
> This is done to limit our reliance on a single CI provider.

I was always under this impression as well. I would support moving away from AppVeyor and using GitHub Actions for all our CI needs, so that it is easier to maintain in the future.
