### ISSUE TITLE
`git` requirement of 2.14 in DG not sufficient for passing test cases

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1728]
**Tell us about your environment**

* **RepoSense Version:** master branch
* **OS and Version:** Ubuntu 18.04
* **Web Browser and Version (if applicable):**
* Git version: 2.17

**Please include the steps to reproduce the bug.**

Precondition: Git version lower than 2.23.0 (2.22.5 or earlier)
1. `./gradlew test`

**What was expected to happen?**
All test cases passed without issue.

**What actually happened?**
About 5 test cases fail with the error message being that `--ignore-revs-file` is not a recognised flag for `git blame`. 

**Relevant information**:
In the changelog for [version 2.23.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.23.0.txt) of git, there is the line `"git blame" learned to "ignore" commits in the history, whose
   effects (as well as their presence) get ignored.` which I think is how `git` documents new flags. 

This version is where the `--ignore-revs-file` and `--ignore-rev` flags were added. 
(Version comparison can be found [here](https://github.com/git/git/compare/v2.22.5...v2.23.0) and the commit https://github.com/git/git/commit/ae3f36dea16e51041c56ba9ed6b38380c8421816 shows the addition of the new flags.)

**Proposed Fix**:
We can either change the DG to require 2.23.0 or later or do something like what is done in `configSystemTest` currently:
https://github.com/reposense/RepoSense/blob/a4ee1877a9fc47abde0592201ae489911a4bb604/src/systemtest/java/reposense/ConfigSystemTest.java#L198-L200

I am more inclined to updating the DG as I think the developers working on the codebase should have sufficient git version to interact with all the currently used `git` features.

**Comment by dcshzj** [comment]
I think the issue is that the git version is not checked properly before the call to `--ignore-revs-file` is called. It should not happen that the flag is still called when we know it is not available to be used (i.e. version is not new enough).

Personally I would prefer if we fix this like how it is done for ConfigSystemTest. A couple of reasons:
1. At least for Ubuntu 18.04 LTS, the [bundled git version is 2.17.1](https://packages.ubuntu.com/search?keywords=git). Increasing the Git version requirement will cause RepoSense to be unusable out-of-the-box for users still on Ubuntu 18.04 LTS. This would be a concern, especially since Ubuntu 18.04 LTS is [still receiving hardware and maintenance support](https://ubuntu.com/about/release-cycle), and we will risk alienating users still using this version.
2. The same argument is valid for Debian as well, where Debian buster is [still using git version 2.20.1](https://packages.debian.org/search?keywords=git) and the end-of-life is expected to be [around June 2024](https://wiki.debian.org/LTS).

I don't think we have a rule of thumb that we follow in terms of the dependencies, but I think at least in this case, we try to maximize our compatibility as much as possible. We can probably bump the requirements to 2.17.1 to match the one provided by Ubuntu 18.04 LTS, and to also match the [last supported version of git](https://en.wikipedia.org/wiki/Git#Releases), but any newer features that we use should ideally ensure that we remain compatible with old supported versions as much as possible.

**Comment by chan-j-d** [comment]
Hmm I was thinking more along the lines of a new developer having the required tools at a sufficiently high version (git 2.14) but being unable to build the project since it fails a test case. At the time of creating this, it didn't cross my mind that the same issue exists in the main codebase.  

I went to double check and it seems like the UG also has the same version requirement though I haven't actually checked if the jar file can run properly since i updated my git version to hot fix the build failure.
