### ISSUE TITLE
Refactoring `processLine` in `RepoConfigCsvParser` class

### ISSUE THREAD

**Issue by gok99** [reposense/RepoSense#1753]
This is a follow-up issue from discussions in https://github.com/reposense/RepoSense/pull/1647#discussion_r841910967

**What ideas would you like to see in RepoSense?**

The `processLine` method is now at more than a 100 lines, and getting hard to maintain. It might be a good idea to break them apart. 

Perhaps the config parser could be broken down into a collection of parser subclasses that are logically related to each other (e.g for parsing columns related to size limit), so that parsing is easier to maintain while avoiding unnecessary proliferation of parsing classes.

**Comment by SkyBlaise99** [comment]
I observed a lot of `logger.warning(...);` within the method. Perhaps I can shorten this method by extracting all the `logger` stuff into a new method that will be called at the end of the `processLine` method?

**Comment by gok99** [comment]
Hey @SkyBlaise99. Moving out the logging would certainly reduce the method length but will probably adversely effect code quality. Some concerns:
- Method calls to the new logger method would probably need a very large (and ever growing) number of arguments. So, maintenance unpleasantness might just get shifted from `processLine` to the new logger method.
- Logging close to where relevant variables/flags are declared tends to help with readability since related information is intuitively clumped together.
- Seems like might be a temporary fix, since with enough new csv columns, the `processLine` method length will grow back to an undesirable length anyway.

**Comment by SkyBlaise99** [comment]
I see, let me think about it again. Thank you.

**Comment by SkyBlaise99** [comment]
To address your conserns, I tried a new way. Code is available [here](https://github.com/SkyBlaise99/RepoSense/blob/trial-refactor-processLine/src/main/java/reposense/parser/RepoConfigCsvParser.java#L78).

Instead of calling the log msgs at the end, each msg is now called right after the variables are initialized with its value, just like how the current program flow is.

So for a typical part of the code,

``` java
String ignoreFileSizeLimit = get(record, IGNORE_FILESIZE_LIMIT_HEADER);
boolean isFileSizeLimitIgnored = ignoreFileSizeLimit.equalsIgnoreCase(IGNORE_FILESIZE_LIMIT_KEYWORD);

if (!isFileSizeLimitIgnored && !ignoreFileSizeLimit.isEmpty()) {
    logger.warning(
            "Ignoring unknown value " + ignoreFileSizeLimit + " in ignore filesize limit column.");
}
```

It is now shortened to just

``` java
boolean isFileSizeLimitIgnored = matchValueAndKeyword(record, IGNORE_FILESIZE_LIMIT_HEADER,
                IGNORE_FILESIZE_LIMIT_KEYWORD);
```

where `matchValueAndKeyword()` will print to the logs. I have extracted out the last part of adding config into a separate method.

Do you think this a good way to shorten it for now? 

I do agree that eventually,

**Comment by SkyBlaise99** [comment]
Hi @gok99 any feedbacks? Or would it be better if I make a PR to show you.
