### ISSUE TITLE
Top end of the vertical scroll bar in code panel is not visible

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#184]
Posting it as an issue in case you have forgotten @ongspxm 

![image](https://user-images.githubusercontent.com/19277206/42625042-663186d2-85f9-11e8-8636-8a34a7ff0b0f.png)

**Comment by ongspxm** [comment]
eh... looked into it, the reason we have to design it like this is because of this button

![image](https://user-images.githubusercontent.com/1430854/42673426-009252f2-869e-11e8-9e32-b46c37de2286.png)

*ui suggestion*
if we do away with this button, and place the closing button on the top bar, maybe we can show the full scrollbar?

**Comment by yong24s** [comment]
Alternatively, this panel can also be closed by clicking anywhere outside of the side panel.

**Comment by eugenepeh** [comment]
I think, would it be better if we do a separate page for authorship instead? There is kinda little to no benefit to have it together with the ramp charts. E.g. The search bar / date range etc doesn't affect the code panel at all, and its limited to half screen.

If we make a separate page for authorship, we can add a search bar dedicated to the code panel, allows searching for particular file, ext etc.

**Comment by damithc** [comment]
> Would it be better if we do a separate page for authorship instead? There is kinda little to no benefit to have it together with the ramp charts. E.g. The search bar / date range etc doesn't affect the code panel at all, and its limited to half screen.

I think the two needs to be together. From the tutor's POV, 'how much did this guy contribute?' and 'how well did he do it?' are two questions that go together. It's better to have as much visualizations in the same place so that they can provide context for each other and holistic conclusions can be drawn from them.

We can tweak the control panel to be clearer in future versions. e.g., have separate areas for controls of authorship, contributions, etc. If it needs more space, we can even use a pop-up modal to present the full controls to the user when the user wants to edit the settings. In that case , the control panel on top of the page can show a (read only) summary of current settings.
