### ISSUE TITLE
Frontend DevOps: Upgrade Node to 16 then 18

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1872]
**What feature(s) would you like to see in RepoSense?**

Node 14 will reach [end-of-life](https://github.com/nodejs/release#release-schedule) on 30 April 2023. Although Node 16's EOL would usually be 1 year later, it has been pushed forward to 11 September 2023 since OpenSSL 1.1.1 is also [no longer supported](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on the same day.

**If possible, describe the solution**

The Node version needs to be updated in `build.gradle` as well as our workflows under the `.github` directory.

Suggested upgrade step:

1. Upgrade to Node 16 before 30 April 2023. 
2. Upgrade to Node 18 before 11 September 2023

The rationale for doing this is so that it is easier to resolve any breaking changes.

**Additional context**

You may want to keep #1871 in mind while working on this.

**Comment by ckcherry23** [comment]
For first-time contributors, we have already updated Node to version 16 in PR #1956. Please help update Node to version 18 using the same PR as a reference.

**Comment by sopa301** [comment]
I tried working on this, but was unsuccessful. Here are some things I learnt:

- Updating Node to 18 requires [node-sass](https://www.npmjs.com/package/node-sass) to be updated to at least 8.0
- However, node-sass has been [depreciated](https://sass-lang.com/blog/libsass-is-deprecated/) in favor of dart-sass (sass), which is already used in the project.
- Additionally, node-sass on windows has a few more [requirements](https://github.com/sass/node-sass#install) that make it harder to set up.
- Therefore, it would be easier to remove node-sass and use sass exclusively.
- Attempting to do so resulted in a bug similar to #1784 , but the cause is unclear.
