### ISSUE TITLE
Add embeddable ramp widget

### ISSUE THREAD

**Issue by MarcusTXK** [reposense/RepoSense#1894]
**What feature(s) would you like to see in RepoSense?**

The ability to copy a link for an embeddable ramp widget with the click of a button and embed the ramp widget into any existing website will be a useful feature. This allows users who intend to feature any contributions made to a repository/projects in their portfolio/any website, especially as I feel it is both eye-catching and provides alot of useful information.

Ideally, the embedded ramps should follow any filters configured by the users above so that the information displayed by the ramps can be customized.

![image](https://user-images.githubusercontent.com/50147457/216826125-bd3131e3-e775-4433-bd56-ee97af6793b4.png)

**If possible, describe the solution**

This is supported by Vue.js as it allows the building of [standard Web Components](https://vuejs.org/guide/extras/web-components.html) that can be embedded in any HTML as stated in their docs [here](https://vuejs.org/guide/extras/ways-of-using-vue.html#embedded-web-components).

**Comment by damithc** [comment]
Related but different feature: I would also like to be able to embed the entire report into a web page so that the RepoSense reports can be integrated into other dashboards ([example](https://nus-cs2103-ay2223s2.github.io/dashboards/contents/ip-progress.html) -- currently, the 'code dashboard') links send the viewer to a different website).
