### ISSUE TITLE
Hard to read label text for some dark label colors

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1998]
e.g., 
![image](https://user-images.githubusercontent.com/1673303/234742405-643b1bea-a7a0-4734-a6fb-7a7d0b23f3a8.png)

**Comment by jq1836** [comment]
Looking into this bug, it seems that it is caused by an issue with the method `c-summary: getFontColor`,
```
getFontColor() {
  return window.getFontColor;
}
```

along with its usage in the following block of code found in lines 102-105 in `c-summary.vue`.

```
label(
  v-bind:style="{ 'background-color': fileTypeColors[fileType], \
  'color': getFontColor(fileTypeColors[fileType])}"
)
```

Due to the `getFontColor` method not having any input parameters, the usage of `getFontColor(fileTypeColors[fileType])` becomes invalid and results in the bug.

***Note:***
There is existing logic to decide text colour based on the RGB value of the label's background in `frontend/src/utils/api.ts`, which at least for this case would result in the dark blue label having white text.
