### ISSUE TITLE
Fix failing cypress test for range changes in chartview 

### ISSUE THREAD

**Issue by MarcusTXK** [reposense/RepoSense#2111]
### What was expected to happen?

Currently the following frontend test cases are failing in the github CI

```
  1) range changes in chartview should reflect in zoom
       selecting the initial righthand and lefthand boundary:

      Timed out retrying after 30000ms
      + expected - actual

      -'[2019-12-31] [#785] ChartView: fix authors with unaccounted lines (#789): +49 -42 lines '
      +'[2019-12-20] [#46] Show total time after batch processing (#758): +43 -0 lines '
      
      at Context.eval (webpack:///./tests/chartView/chartView_zoomFeature.cy.js:270:7)

  2) range changes in chartview should reflect in zoom
       changing the righthand boundary:

      Timed out retrying after 30000ms
      + expected - actual

      -'[2019-12-31] [#785] ChartView: fix authors with unaccounted lines (#789): +49 -42 lines '
      +'[2019-12-20] [#46] Show total time after batch processing (#758): +43 -0 lines '
      
      at Context.eval (webpack:///./tests/chartView/chartView_zoomFeature.cy.js:296:7)
```

### What actually happened? Please include a screenshot of the output.
![image](https://github.com/reposense/RepoSense/assets/50147457/01eaa660-66a5-448b-b731-6ad2d864e938)

Link to one such failing CI instance
https://github.com/reposense/RepoSense/actions/runs/7862260141/job/21464243013?pr=2078#step:10:415

**Comment by jonasongg** [comment]
Just investigating for a bit, this might be caused by the ramp shrinking as time goes on (since the until date is not set, defaults to today).

For now, I managed to fix this by setting "until" in the filters to an arbitrary time in the past before this problem arose (I chose 31/12/2023)

![image](https://github.com/reposense/RepoSense/assets/120372506/41a14aa9-9e4c-49b4-a573-dce6599df0b4)

This seems to be the same problem as #2066. Let me know if this fixes the problem for you and if I should create a PR for this!

**Comment by MarcusTXK** [comment]
Hi @jonasongg, thanks for the quick investigation. I think your suggestion is a good way to solve it, works for me too. Yeah I think it is fine to just set an arbitrary time as this will prevent the issue from happening again as more time passes. Please do feel free to create a PR for this if you have the time to do so.

**Comment by ckcherry23** [comment]
Hi @jonasongg, I'd recommend prioritising the PR to fix this first as other PRs would be blocked from merging until all CI tests pass. Thank you!
