### ISSUE TITLE
Remove contribution for white line changes

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#308]
Addition of white line add to lines count in code view.

This shouldn't be the case as white line changes do nothing useful
in production.

**Comment by damithc** [comment]
In keeping with our policy of showing the reality, not draw conclusions, it's best to show a breakdown of empty and non-empty lines (rather than omit them altogether) and in future, break down by other ways such as the file type. 

In theory, even adding blank lines can be a useful contribution as they can improve readability of code.

**Comment by damithc** [comment]
Showing a breakdown of blank and non-blank lines is being done elsewhere. Closing.
