### ISSUE TITLE
If author info is not specified, show only those who contributed during analysis period

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#341]
Current: if author info is not specified, RepoSense shows all contributors for the entire history of the repo

Suggested: show only those who contributed during the analysis period as that is more likely to be the user's intention.

**Comment by eugenepeh** [comment]
> Suggested: show only those who contributed during the analysis period as that is more likely to be the user's intention.

A little tricky here because a simple solution will be simply drop the authors who have no contribution at the end of the analysis. However because user can add authors who have zero contribution in the author-config, we can't do that.

I guess we can add an attribute to the Author model to indicate whether it is compulsory to include in the report, and drop the others who have no contribution afterward.

**Comment by damithc** [comment]
> A little tricky here because a simple solution will be simply drop the authors who have no contribution at the end of the analysis. However because user can add authors who have zero contribution in the author-config, we can't do that.

This issue is about the case where no author config is provided.  In that case we can drop everyone who doesn't have a contribution? If the author config is provided, we have to show all authors mentioned irrespective of whether they have contributions.

**Comment by damithc** [comment]
In a future version, we can also add a parameter to indicate if non-contributors should be listed.

**Comment by eugenepeh** [comment]
Hmm... nvm, found an easier way to do this.

`git log --pretty=format:"%an" --after="2017-02-31" --until="2017-03-10"`
