### ISSUE TITLE
Show breakdown of blank line for total contribution in code panel

### ISSUE THREAD

**Issue by apoorva17** [reposense/RepoSense#427]
Code Panel currently shows the total LOC, which includes both blank and non-blank lines. It would be good if the code panel could also show a breakdown of the blank lines and non-blank lines i.e. ```(Blank: 200, Non-Blank:1800)``` Such a breakdown provides a better understanding of the actual amount of code contributed by the author.
![screen shot 2018-12-13 at 2 38 43 pm](https://user-images.githubusercontent.com/19278550/49920631-db98f300-fee5-11e8-8bd6-1701c355b59b.png)

**Comment by apoorva17** [comment]
@reposense/devs @damithc kindly provide ur feedback for this issue

**Comment by damithc** [comment]
Should we show the breakdown for each file type too?

**Comment by damithc** [comment]
> Would this be too much information for the user to view in the code panel, especially when there are many file types?

It's fine, because there is no way for the user to find that information unless we don't provide it. We just need to figure out how to provide that information without overwhelming the user. For example, the breakdown for file types can be shown as a tool tip. 

You can implement the file-type breakdown in a later PR. Just keep that in mind when you implement this one.

On a related note, let's not use red for the whole text. We can use red just for the important info such as the file type and the total. Unimportant info such as the number of blank lines can be grey.
