### ISSUE TITLE
Code view: support glob filters

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#504]
Current: we can filter the code view by file types, using tick boxes
Suggested: support a more powerful filter box where the user can type a glob e.g., `**/test/*.java`

**Comment by damithc** [comment]
@apoorva17 is interested in doing this.
@eugenepeh this feature requires a toolbar, right? I remember you had some ideas about adding a toolbar for the code view. How do you propose to proceed with this issue?

**Comment by eugenepeh** [comment]
>@eugenepeh this feature requires a toolbar, right? I remember you had some ideas about adding a toolbar for the code view. How do you propose to proceed with this issue?

Yes, I wanted to add a toolbar for code view but, as discussed, we will have to transform the chart view to use a tool bar first to make the 2 view similar. Sorry for the delay in implementation due to dealing with other work and also wanted to get some issues done before the 2103 students come in; will get it up soon.

Meanwhile, I guess since @apoorva17 is interested in doing this feature, perhaps we can settle for a search bar at the top right corner of code view for this PR first? We can subsequently replace it with a tool bar afterward.

**Comment by ongspxm** [comment]
:+1:
