### ISSUE TITLE
Optimizing space for chart view toolbar

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#509]
As the number of selectable fields and options expand, the toolbar is taking up more space in the UI.
We would need to optimize the space to make it neater; customizing the appearance to manifest as a professional tool to the users.

Here's a few mock up design we had in the discussion:
![image](https://user-images.githubusercontent.com/19277206/51660790-cbe2f300-1fe9-11e9-8ac0-67829312151d.png)

and also can consider turning the date range picker into a pop up like google search engine too
![image](https://user-images.githubusercontent.com/19277206/51660835-ecab4880-1fe9-11e9-940c-1ed23500b4d7.png)

Prof suggests that he would like to keep current settings in view even if the controls are not in view. Instead of seeing 'Date Range', he'd rather see the actual date range. 

For that, we can possibly follow the google search bar style where selecting an option updates the title for that drop down field. Though, we can't do this for the checkbox options as there can be multiple output.
![image](https://user-images.githubusercontent.com/19277206/51660909-2f6d2080-1fea-11e9-832f-32a23e8492c7.png)

Will not be working on this issue for now as there seems to be conflict with some ongoing PRs. However, if any of the frontend/ui guys interested in picking up this issue, do let me know so I can work on cleaning up some of the other backend work instead.

**Comment by damithc** [comment]
I'm also in favor of making the default toolbar read-only, showing only the values of more important settings. There will be an `Edit` button that pops up an edit view. The edit view can be as large as we want, and we can optimize it for editing convenience rather than for saving space. The user will change all settings as needed and click the `Apply` button to update the view to match the new settings. This also avoids the current problem of (assuming the user wants to change several settings) each individual setting change being applied to the view rightaway, and the user having to wait till the change is applied before moving onto change the next setting.

**Comment by damithc** [comment]
The toolbar seems to be stable now. Will reopen this at a later time.
