### ISSUE TITLE
IgnoreCommitList: enhance to produce better results

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#569]
IgnoreCommitList removes the authorship of given commits. 
https://github.com/reposense/RepoSense/blob/6dd74a04a3d1da6aa3b1636d0b0a7fdd2f873591/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L94-L97

A better implementation would be to find the authors prior to commits in case of reversion.
Once such use case is as described in https://github.com/nus-cs3281/2019-dashboard/pull/28#issuecomment-466428270 where mass deletion and restoration caused a major shift in the authorship.

To test whether if its possible to achieve this, I've tried 2 solutions.
1. Using [git blame's -c options](https://git-scm.com/docs/git-blame#git-blame--Cltnumgt), in hope to be able to looks for copies from other files in any commit.
2. Using [git replace](https://git-scm.com/docs/git-replace) 

The first option has been tested to be ineffective in the above use case. 

In the second option, I used the command `git replace --graft 9a134979327a17255547ecc0b2f446174da04169 9a134979327a17255547ecc0b2f446174da04169~~` and manage to restore the author prior to the changes.
```
$ git blame "src/lib/markbind/src/handlers/cyclicReferenceError.js"             
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  1) class CyclicReferenceError extends Error {
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  2)   constructor(callStack) {
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  3)     super();
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  4)     const fileStack = callStack.slice(Math.max(callStack.length - 5, 0));
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  5)     this.message = 'Cyclic reference detected.\n'
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  6)         + `Last 5 files processed:${'\n\t'}${fileStack.join('\n\t')}`;
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  7)   }
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  8) }
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800  9) CyclicReferenceError.MAX_RECURSIVE_DEPTH = 200;
a1e9c9ed (Si Jie 2019-02-07 12:13:53 +0800 10) module.exports = CyclicReferenceError;
```

As of now, it is unsure whether this is effective in only this scenario. Do explore the possibility of using the second option to enhance IgnoreCommitList.

**Comment by yamidark** [comment]
I just tested using git replace, don't think it actually works the way we want though.
For the case you try:
Before:
![untitled](https://user-images.githubusercontent.com/18352498/53282991-4c784900-377a-11e9-80a8-eb8d4cce16f4.png)
After:
![untitled](https://user-images.githubusercontent.com/18352498/53283290-17222a00-377f-11e9-85bf-61bc257153d3.png)


What git replace kind of did here is that it 'compressed'/squashed these 2 commits instead, and as since the latter is just a reverting of the previous commit, it end up causing the new squashed commit to become an 'empty' commit', thus the author contribution is able to be attributed to `Si Jie`.

However, if we do use git replace for other commits, it will simply be 'squashed' it so the line authorship will go to that squashed (child) commit, instead of the original author.

For example, I tested by 'removing'/'ignoring' [Jamos Tay commit](https://github.com/MarkBind/markbind/commit/8c6aa3727e874c366e6d24bec4480cf27f7518d5)

By running git blame for that parent commit, the previous line author should have been nicholaschuayunzhi:
![untitled](https://user-images.githubusercontent.com/18352498/53283246-4c7a4800-377e-11e9-9bce-46263ccff718.png)

However, by 'removing'/'ignoring' that commit using git replace (`git replace --graft 8b9b2279000ba404b14e0ec0c3975113288a3e64 8b9b2279000ba404b14e0ec0c3975113288a3e64~~`), that line author becomes Prof Damith instead:
![untitled](https://user-images.githubusercontent.com/18352498/53283259-83505e00-377e-11e9-8d02-c7d533da98d9.png)

**Comment by yamidark** [comment]
Anyway, I found this tool [git hyper-blame](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html), which seems to do what we want (finds the previous author of an edited line), can try this out and see if we can find some way to use this within RepoSense as well.

**Comment by eugenepeh** [comment]
Thanks for the further investigation @yamidark. Didn't have time to do it earlier so i just document whatever I tried so far before going off.

**Comment by yong24s** [comment]
Source code for `git hyper-blame`
https://github.com/google/proto-quic/blob/master/depot_tools/git_hyper_blame.py

**Comment by FH-30** [comment]
Hi, can I try working on this issue?

**Comment by damithc** [comment]
> Hi, can I try working on this issue?

@FH-30 you can give it a try and share what you come up with (e.g., as a draft PR) to get feedback from others. @reposense/active-devs let @FH-30 know if you have objections/inputs.
