### ISSUE TITLE
RepoSense v1.7 inconsistent with user guide documentation

### ISSUE THREAD

**Issue by yash-chowdhary** [reposense/RepoSense#577]
The instructions to run the `.jar` in the UserGuide are inconsistent with the actual working of the `.jar` file of `v1.7` after downloading it from the releases section.

All the arguments according to the UserGuide (like --repo, --view, --until etc.) are invalid in the jar file. The arguments are only accepted with a single hyphen (-repo, -view, -until etc.). 

Here's the output of the help screen:

<img src="https://user-images.githubusercontent.com/21968718/53384232-2d2f1680-3948-11e9-8068-ddcfaa5beda1.png" width="50%" height="50%">

A sample run of an invalid and valid command is shown below:

<img src="https://user-images.githubusercontent.com/21968718/53384595-7764c780-3949-11e9-8535-fec6b9af106c.png">

Since the code itself accepts arguments with 2 hyphens, it is probably the case that a different `.jar` file was uploaded.

**Comment by yong24s** [comment]
@yash-chowdhary 

Thanks for trying out RepoSense!

You are probably reading the User Guide from the `master` branch instead of the `release` branch.

[1] [User Guide in Master](https://github.com/reposense/RepoSense/blob/master/docs/UserGuide.md#getting-started)

[2] [User Guide in Release](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#getting-started)

We could perhaps improve on the instructions to users who are using releases.

**Comment by yash-chowdhary** [comment]
I see. Thank you for the clarification!

**Comment by eugenepeh** [comment]
>We could perhaps improve on the instructions to users who are using releases.

Hmm the links on the landing page do direct user directly to user guide of our release.
Well to simplify things further, I have added the documentation links in the release. 
Closing this issue...
