### ISSUE TITLE
Remove unused MethodInfo and ConfigurationBuilder

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#619]
When running coverage for RepoSense, I found that there are two classes that are never used in our codebase, `MethodInfo` and `ConfigurationBuilder`.

If they are not in our immediate plan, we should remove them from our code.

**Comment by fzdy1914** [comment]
@yamidark Can give information on if `MethodAnalyzer` and `ConfigurationBuilder` is still needed in our code base?

**Comment by yamidark** [comment]
@fzdy1914 

I believe `MethodInfo` is related to `MethodAnalyzer`, which also isn't used at all. Seems to be legacy code from pre-v1.0. 

From what I can understand from the code, `MethodAnalyzer` seems to assume the file is in `.java` format, and compiles it so that it can go through each method 1 by 1, and identify its 'author' based on the most number of lines contributed to the method.

As RepoSense now targets any file formats instead of just `.java` format, I believe this method isn't useful for us anymore.

@damithc Just to check, may I know if there are any plans to identify authors of 'methods' (along with lines) as well?


`ConfigurationBuilder` also seems to be legacy code from pre-v1.0 and never used at all. Doesn't seem to be have much use in our main production code, since we are constantly updating the values in the `RepoConfiguration`, from the `StandaloneConfig` or `CliArguments`. 

However, this may be useful as a test util class for constructing `RepoConfiguration` in our testing (improve readability).

@eugenepeh Your opinion on this?

**Comment by damithc** [comment]
> @damithc Just to check, may I know if there are any plans to identify authors of 'methods' (along with lines) as well?

No. We can remove any related code if no longer needed.

**Comment by fzdy1914** [comment]
> However, this may be useful as a test util class for constructing `RepoConfiguration` in our testing (improve readability).

Actually, the current `ConfigurationBuilder` is not so helpful for testing. If we want to use `ConfigurationBuilder` in our test case, it can be added back in a separate PR.
