### ISSUE TITLE
Oracle JDK 8 is NOT installed.

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#648]
Travis has broke down
https://travis-ci.org/reposense/RepoSense/jobs/521573562#L476

**Comment by yong24s** [comment]
The `oracle-java8-installer` in our `.travis.yml` refers to `ppa:webupd8team/java` repository.

https://github.com/reposense/RepoSense/blob/7640e703acbcfbb55699c80dd4ca53add97511e4/.travis.yml#L8-L11

According to https://launchpad.net/~webupd8team/+archive/ubuntu/java, the repository has been discontinued due to licensing issues.
