### ISSUE TITLE
Weird behavior of contribution bar

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#706]
The contribution bar shows user's contribution of the whole range but not filtered one. It displays value even there are no commits in the range. 

![a](https://user-images.githubusercontent.com/35621726/58339387-141cff80-7e7c-11e9-8812-995f0744c89a.gif)

**Comment by jamessspanggg** [comment]
Yes I have noticed this too but I saw the UserGuide stating that the modifying the since date and until date won't affect the contribution bar:
<img width="700" alt="Screen Shot 2019-05-25 at 1 12 36 AM" src="https://user-images.githubusercontent.com/32864116/58345188-59482e00-7e8a-11e9-835f-68f8838a26a9.png">

**Comment by damithc** [comment]
Yes, that is the expected behavior. I believe it is is not possible to precompute contribution for any possible duration and the frontend doesn't have enough data to compute it on demand.
