### ISSUE TITLE
Add a sample repo for filesystem test

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#726]
We should probably have a sample repo within our repository for file system test on report

**Comment by dcshzj** [comment]
I'm not sure what the file system test is referring to, @eugenepeh are you able to elaborate more on this issue?

**Comment by chan-j-d** [comment]
Closing this issue as there have been no recent updates and I believe the original intention of the issue was to have a local repo stored within the reposense repository to perform system tests on local repos which has been covered by https://github.com/reposense/RepoSense/pull/1746, albeit remote cloned first and then reposense run as if it were a local repository.
