### ISSUE TITLE
Deal with "--ignore-standalone-config" when parsing config files

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#736]
Current: when parsing CLI with CSV configs, `--ignore-standalone-config` is ignored (no errors/warnings shown to the user).

Suggested: Terminate the program (with error message) or warn the user if user sets `--ignore-standalone-config` when using CSV configs. 

Reason: Users might not be aware that the ignore flag has to be set in the csv file when parsing in .csv files.

**Comment by anubh-v** [comment]
Would a warning suffice, or should we terminate the program as well?
The warning could be similar to: `Disregarding --ignore-standalone-config flag, please set this flag within the repo-config csv`.

**Comment by anubh-v** [comment]
@yong24s, @damithc, @eugenepeh  may I seek your opinions on how this issue is best resolved?

We have the choice of either warning the user that the` --ignore-standalone-config` flag will be ignored OR terminating the execution of RepoSense.

In the current implementation at #928 , I've chosen to issue a warning.

However, perhaps it is better to terminate the program? 
Terminating the program would clearly highlight the incompatibility of `--ignore-standalone-config` with `--config`. This information might be missed if we only provide a warning.

**Comment by damithc** [comment]
Another possibility is for the CLI parameter to override the one specified in the csv file, possibly with a warning. That way, it is easy to set this flag for all repos without having to add it to every line in the csv file. What do you guys think?

**Comment by anubh-v** [comment]
> Another possibility is for the CLI parameter to override the one specified in the csv file, possibly with a warning. That way, it is easy to set this flag for all repos without having to add it to every line in the csv file. 

I think this approach is appropriate. It provides more utility for users than the alternatives of terminating the program / disregarding the `--ignore-standalone-config` flag.

Additionally, it will be more consistent with our approach for the `--formats` option, which also appears in both the command lines options and `repo-config.csv`.

Instead of specifying the same file format on each line of `repo-config.csv`, users are able to specify the format once using the `--formats` command line option.

**Comment by damithc** [comment]
IIRC, we allow both CSV and CLI to be used for the format, but CLI doesn't override the CSV. My gut feeling is that CLI should take higher precedence. Also, whichever we choose, it should be uniform across RepoSense.

**Comment by eugenepeh** [comment]
@anubh-v please refer to https://github.com/reposense/RepoSense/issues/430

**Comment by anubh-v** [comment]
@damithc, could I get your thoughts on whether my proposal for solving this issue is acceptable?

**Comment by eugenepeh** [comment]
>For example, if we adopt the inherit / default mechanism mentioned in #430, then repo-config.csv may not even need a Ignore standalone config column. Note that this is just one possibility and issue #430 is still under discussion.

For now, can just retain the `Ignore standalone config column` to not complicate the problem as highlighted in #430 , that can be left as a further work.

**Comment by damithc** [comment]
> @damithc, could I get your thoughts on whether my proposal for solving this issue is acceptable?

I'm OK with it.
