### ISSUE TITLE
Enhance zoom tab

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#778]
In addition to zooming into details, zoom tab also shows the breakdown the commits, this functionality however, is not encompassed for the whole ramp chart

Let's add a button that opens zoom tab for the entire ramp chart.

**Comment by jamessspanggg** [comment]
> Let's add a button that opens zoom tab for the entire ramp chart.

Does this mean that the ramp chart in the zoom tab basically shows the entire ramp chart from ChartView but with ramp slices in terms of `commit`?

Note: I have an ongoing PR #729 that modifies the zoom-in functionality to display the zoomed-in ramp chart that is based on the selected granularity (instead of the current implementation of always be in terms of `commit`). For eg: the ramp chart in zoom tab will show ramp slices in terms of `week` when granularity set to `week`. 

Is the zoom-in feature intended to basically zoom-in to show the ramp chart in terms of `commit`? If that is the case, then I would have to make changes to my PR.

**Comment by damithc** [comment]
> Does this mean that the ramp chart in the zoom tab basically shows the entire ramp chart from ChartView but with ramp slices in terms of `commit`?

It can be of in whichever granularity chosen by the user.
