### ISSUE TITLE
Weird analysis result for recent one month

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#785]
In our [netlify preview](http://reposense.netlify.com/), there are two authors in reposense who have contribution bar but no ramp. We need to investigate why it happens. (May related to co-authorship)
![image](https://user-images.githubusercontent.com/35621726/60497127-c7341080-9ce6-11e9-87f3-cc2474262a7f.png)

**Comment by jamessspanggg** [comment]
**Investigation**
By investigating the same report above, in particular for the author Jun An, the code changed is shown below:
<img width="500" alt="Screen Shot 2019-07-03 at 2 55 08 PM" src="https://user-images.githubusercontent.com/32864116/60569834-ceb8ef80-9da2-11e9-9eac-40817b0dda3f.png">

The changed code belongs to the commit by jylee-git's merged PR #728 
<img width="500" alt="Screen Shot 2019-07-03 at 2 56 15 PM" src="https://user-images.githubusercontent.com/32864116/60569986-2a837880-9da3-11e9-8535-bbd1b3eb324a.png">

Checking the git blame of the file shows that jylee-git is the most recent author:
<img width="1219" alt="Screen Shot 2019-07-03 at 2 59 52 PM" src="https://user-images.githubusercontent.com/32864116/60570156-8221e400-9da3-11e9-970e-a1889d9be526.png">

When viewing the git blame of the same file prior of the change, the author was Jun An:
<img width="1244" alt="Screen Shot 2019-07-03 at 3 00 41 PM" src="https://user-images.githubusercontent.com/32864116/60570234-b7c6cd00-9da3-11e9-9588-87aea38f5b6c.png">

**Conclusion**
I think why jygit-lee is not recognised as the author of line 117-119 is because jylee-git basically only removed the try catch block, but not modifying the contents of line 117-119 (only the position of the 3 lines). Hence, the previous author (Jun An) will be recognised as the author.

**Comment by damithc** [comment]
It still feels like an anomaly though. The code should not be in the chart because Jun An didn't contribute the code during the analysis period. Not sure if it is practical for RepoSense to identify this kind of situations and omit such code from the view. Need to investigate how much work/complexity that would cost us.

**Comment by jamessspanggg** [comment]
I found out that it is due to our git blame command. 
Our git blame command is: git blame -w --line-porcelain FILE

With the -w (Ignore whitespace when comparing the parent’s version and the child’s to find where the lines came from), since there are no changes in the content of those lines (but only shifting the position of those lines), the previous author will be recognised as the author.

Is -w necessary for our git blame?

**Comment by damithc** [comment]
> Is -w necessary for our git blame?

It _does_ improve the accuracy of the picture. In this particular case, it is not right to attribute those line to jylee-git as they were actually written by Jun An.

**Comment by jamessspanggg** [comment]
Okay in that case, we might need to have an extra check for the date committed of each line. If the date is not within the analysis date, we won't include that line.

The same example as above, Jun An committed these lines during 2018-07-20, we can have check if that date is within the specified analysis date.
<img width="1127" alt="Screen Shot 2019-07-03 at 4 32 45 PM" src="https://user-images.githubusercontent.com/32864116/60576706-7b4d9e00-9db0-11e9-9653-185bbeea4a76.png">

**Comment by damithc** [comment]
> Okay in that case, we might need to have an extra check for the date committed of each line. If the date is not within the analysis date, we won't include that line.

Sounds good, as long as it can be done at a reasonable cost.
