### ISSUE TITLE
Error message of command line

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#805]
Running command `gradlew run` on windows gives the following error:
![image](https://user-images.githubusercontent.com/35621726/60977902-cfcdbc00-a362-11e9-8817-d4eaafae7758.png)

**Comment by jylee-git** [comment]
That's because `testrepo-Empty` is an empty repository. So when you attempt to validate file paths in `master` branch (which does not even exist in the first place), runtime error gets caught, which in turn throws GitClone exception.

I think the issue here is with the improper displaying of message and the . PR #765 implicitly deals with this issue, where `GitBranch` exception will be thrown when the branch does not exist.

**Comment by fzdy1914** [comment]
@jylee-git Thanks for the investigation, I thought we already fixed this issue in this PR(https://github.com/reposense/RepoSense/commit/49c46a4d746d212ce113813cc6fa630a18d55b74).
