### ISSUE TITLE
AnnotatorAnalyzer: Bug in code disowning mechanism

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#823]
### Refer to the report here: https://reposense-issue-823.netlify.com

![image](https://user-images.githubusercontent.com/35756209/61517865-cddabb80-aa3a-11e9-86dc-832430011786.png)

 git-id `some-randomuser` did not make any commits to that repo. Should the following 3 lines (7-9) still be tagged to the person who wrote the code?

![image](https://user-images.githubusercontent.com/35756209/61517898-e21eb880-aa3a-11e9-9550-f280d61950c3.png)

Should the `@@author` tag (line 13) be tagged to an author? Even so, the tag is written to `rjcai-tee` who did not write the `@@author` tag.

**Comment by damithc** [comment]
Every line (including the `@@author` line) should be attributed to the person who wrote it. No special treatment needed for `@@author` lines. Does that clarify the situation?

**Comment by jylee-git** [comment]
> Every line (including the `@@author` line) should be attributed to the person who wrote it.

Ok noted.

But what about the first part where `some-randomuser` dosen't exist but `@@author some-randomuser` is present? Should lines 7 to 9 still be attributed to (me) or `some-randomuser`?

**Comment by damithc** [comment]
It should be attributed to `some-randomuser`.  This is a way to disown code, for example, because it was taken from somewhere else and you don't wish to claim credit for it.

**Comment by jylee-git** [comment]
> It should be attributed to `some-randomuser`. This is a way to disown code, for example, because it was taken from somewhere else and you don't wish to claim credit for it.

Ok then. I suppose that we will treat this as a bug and fix it

**Comment by anubh-v** [comment]
I investigated this bug.
The problem seems to lie in `AnnotatorAnalyzer#aggregateAnnotationAuthorInfo`.

Code snippet:
https://github.com/reposense/RepoSense/blob/6fe782466dc827ab5c37c095000dfaba6e2ee3db/src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java#L25-L46

The bug arises because:
(1) When `@@author some-randomuser` is used in the file, `AnnotatorAnalyzer` considers this annotation to correspond to the `UNKNOWN_AUTHOR` (which is a predefined Author object)

(2) The `aggregateAnnotationAuthorInfo` method only allows the annotation override to take effect **if the author is not UNKNOWN_AUTHOR**.

The end result: code blocks are never attributed to `some-randomuser`.
(To be specific, only the line containing `@@some-randomuser` and the end tag will be attributed to `some-randomuser`. Lines between the tags are not attributed to `some-randomuser`.)

To solve this, I think we should change the logic in `aggregateAnnotationAuthorInfo`.

Instead of this check:
https://github.com/reposense/RepoSense/blob/6fe782466dc827ab5c37c095000dfaba6e2ee3db/src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java#L42

we could keep a boolean flag that indicates whether the method is currently processing a code block marked with an annotation override.

**Comment by anubh-v** [comment]
@jylee-git, could we rename this issue's title so that bug is more understandable to other devs?

Perhaps the title can be: `AnnotatorAnalyzer: Bug in code disowning mechanism`
I can help to edit it, but I do not have the permissions currently.

**Comment by jylee-git** [comment]
> @jylee-git, could we rename this issue's title so that bug is more understandable to other devs?
> 
> Perhaps the title can be: `AnnotatorAnalyzer: Bug in code disowning mechanism`
> I can help to edit it, but I do not have the permissions currently.

Done!
