### ISSUE TITLE
Use single package.json

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#861]
In our project, there are two `package.json` files. One is located in the `root` directory and another is located in `frontend/cypress`.

Let's combine them, so cypress `npm tasks` can be run at `root` directory, for easier management and usage.

**Comment by anubh-v** [comment]
@yong24s, I have a question about the value of merging the `package.json` files.

I understand that the `package.json` at `frontend/cypress` specifies some `npm scripts` related to Cypress. However, we can already run these scripts from the project `root` directory using `gradlew`, since the `build.gradle` file specifies the correct working directory for `npm`.

Hence, what's the expected benefit of merging the `package.json` files?
Thanks for your time!

**Comment by yong24s** [comment]
@anubh-v, thanks for your interest in this issue.

I couldn't find the actual comment, which suggested the use of a single package.json. I believe it has to do with the convenience of having all npm tasks exposed at the project root level.

> However, we can already run these scripts from the project root directory using gradlew, since the build.gradle file specifies the correct working directory for npm.

Using `gradlew` doesn't run the system's npm, but a portable version from gradle.

> Hence, what's the expected benefit of merging the package.json files?

You raised very good points. On a second thought, having them separated would be easier for maintainability.

**Comment by fzdy1914** [comment]
Should we close this issue for now?
