### ISSUE TITLE
Generalize handling of git exceptions 

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#863]
As discussed in https://github.com/reposense/RepoSense/pull/743#discussion_r298622966, let's generalize handling of git exceptions and their messages which are shown on the report.

**Comment by anubh-v** [comment]
@yong24s, thanks for raising this issue.

I looked at the discussion that you linked, but I'm still not clear about the problem with the current method of handling git exceptions.

I see that various git exceptions (`GitBranchException`, `GitCloneException`, `InvalidFilePathException`) are handled within the `analyzeRepos` method of `ReportGenerator`.

I also observe that we store the error messages for these exceptions within the `ErrorSummary` instance.

What exactly is the limitation with the current implementation, and what's the ideal case? I'm not clear what you mean by "generalising" the handling. 

Are you suggesting that `ErrorSummary` should store exceptions rather than error messages, and each exception should store its own error message?

Thanks for explaining!
