### ISSUE TITLE
csv files: ignore blank lines

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#871]
In csv config files, we can ignore blank lines rather than abort upon encountering a blank line.

**Comment by anubh-v** [comment]
Hi all,
I have investigated this issue, and am recording my findings here to help clarify this task.
I define "blank line" as a line that has only whitespace characters, and at least 1 whitespace character. I defined "empty line" as a line with 0 characters.

1) RepoSense crashes when there are one or more blank lines **before** the header of the
 `repo-config.csv` file. Reason: 
  a) Due to the preceding blank lines, every line in the actual CSV data gets considered as *malformed*. 
  b) Hence, none of the repositories' configurations are captured. 
  c) The subsequent `ReportGenerator` code assumes that we have at least 1 repository to analyze, resulting in an index out of bounds exception.

2) RepoSense **does not crash** when there are blank lines **after** the header of the `repo-config.csv` file. These blank lines are considered *malformed* and ignored.

3) Placing empty lines anywhere in `repo-config.csv` does not cause crashes.

To resolve this issue, I'll check if the `CSVFormat` class supports the ability to ignore blank lines before the header.
