### ISSUE TITLE
ConfigCsvFiles: Improve exception handling when the csv file(s) is/are malformed

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#872]
For example, `author-config.csv` should contain 7 columns (especially the headers). However, the user provided 6 columns (fewer columns than requred).

When program is run, exception is caught but the program is terminated abruptly, without giving the user enough info as to where went wrong:
![image](https://user-images.githubusercontent.com/35756209/63599911-216d9580-c5f5-11e9-861c-c7930104eab5.png)

###To-do
Improve on the exception handling, by informing the user that the csv file does not contain the required number of columns

**Comment by anubh-v** [comment]
I think this issue can be broken into 2 related issues:

A) The user provides the correct number of columns in the header, but every record is malformed. This could happen because every record either has fewer / more columns than the header, or lacks data in mandatory columns.

In this case, RepoSense will not register any of the CSV records in the generated List of RepoConfigurations. It would be good to alert the user when this happens.

Note that when this issue occurs in the `repo-config.csv` file, then RepoSense will end abruptly just as mentioned in this issue, because RepoSense currently expects at least 1 repository to be specified in `repo-config.csv`.

B) The user provides fewer columns than required in the header, and the records are technically not malformed. In this case, RepoSense ends abruptly as shown by @jylee-git . As mentioned by @jylee-git, it would be good to provide more helpful exception messages.

**Comment by anubh-v** [comment]
Here are my proposed solutions for the 2 issues identified above:

To solve, issue A, we could use the logger to explicitly warn the user that **all** the records in the CSV have been considered malformed. In the case of `repo-config.csv`, we should throw an exception since the file is not optional.

To solve issue B, we could perform validation on the size of the header in the CSV to ensure the number of columns in the header are as expected.

**Comment by jylee-git** [comment]
The reason for this issue is as follows (in technical terms): 
Take an example of `repo-config.csv`, which has 6 header columns. Only the first column (repo location) is required. The rest of the fields are optional.

The apache CSV parser used will parse these CSV files by detecting the number of header columns into `CSVRecord` with a fixed size of columns. So if the number of header columns are lesser than the original 6 columns (let's say the `repo-config.csv` file provided only has 4 columns), each CSVRecord generated will contain the row of data of size 4 (indexes 0-3).

In the program to process these CSVRecords, the program will check if the user provided any data for columns 4 and 5. But because the CSVRecord only has 4 columns, so ArrayOutOfBoundsException occurs here, and terminates the program because the exception isn't handled well here.

The ultimate aim here is to ignore that row, warn the user that the line/row is malformed, and continue analyzing the rest.


------------------------------------------------
Anw replying to your proposals and clarifying on some things:

> The user provides the correct number of columns in the header, but every record is malformed. This could happen because every record either has fewer / more columns than the header, or lacks data in mandatory columns.

Some of the fields are optional. So the user can provide fewer columns for the data fields than the number of header columns, provided that all the mandatory columns are filled up. So given an example of `repo-config.csv` (note that only the repository field is required), this is OK:

| Repository (required) | Branch | File format | Ignore Glob List | Ignore Standalone Config | Ignore Commits List |
| ----------------------- | --------------------| ---------------------|------|-----|-----|
| https://.../reposense.git| | | |
| https://.../alpha.git| master | | |
| https://.../beta.git| | java | |

But this is not OK: 

| Repository (required) | Branch | File format | Ignore Glob List | Ignore Standalone Config | Ignore Commits List |
| ----------------------- | --------------------| ---------------------|------|-----|-----|
| | master | java | ... | ... | ... |

---------------------------------------------------
> To solve, issue A, we could use the logger to explicitly warn the user that **all** the records in the CSV have been considered malformed.

There is already an existing functionality that warns the user that the particular line is malformed. If all lines are malformed it will be printed `n` times s.t. `Line n in CSV file.... is malformed...`. Not sure if warning the user that **all** the records are malformed would be useful but we can leave that in a new issue.

![image](https://user-images.githubusercontent.com/35756209/65370440-3dfbfc80-dc8b-11e9-901f-16bea94e5d2b.png)



> In the case of `repo-config.csv`, we should throw an exception since the file is not optional.

If the `repo-config.csv` is not found, the program will terminate and inform the user that the file is not found in the specified folder, so there's no issue here.

> 
> In this case, RepoSense will not register any of the CSV records in the generated List of RepoConfigurations. It would be good to alert the user when this happens.

Yes we should inform the user something like "nothing to analyze" and terminate the program.


> To solve issue B, we could perform validation on the size of the header in the CSV to ensure the number of columns in the header are as expected.

Yes I think we should do that.

**Comment by anubh-v** [comment]
Thanks for your response @jylee-git.

I'll address this task by implementing 2 checks:

1. Check that the size of the header in the CSV config is correct.

2. Check that there is at least 1 valid record in the `repo-config.csv` file.

**Comment by anubh-v** [comment]
> Check that there is at least 1 valid record in the repo-config.csv file.

I have created a separate issue for this. Please see issue #942
