### ISSUE TITLE
Commits panel: Capture and display tags beside each commits

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#879]
With CS21x3 making use of git tags actively, we can consider enhancing the commits panel such that tags (if any) are captured and displayed beside the commit as well.

**Comment by damithc** [comment]
Good idea 👍 
I wonder if they can be shown as part of the ramp chart too.

**Comment by jamessspanggg** [comment]
Hi prof, how do you want the tags to be shown in the commits panel?

I have tried implementing where if the commit has a tag, it will show the following (if commit has no tag, the icon and text will not be shown):
<img width="815" alt="Screen Shot 2019-12-15 at 11 44 06 PM" src="https://user-images.githubusercontent.com/32864116/70865137-f38dd180-1f94-11ea-8977-79167a9acdfb.png">

**Comment by damithc** [comment]
Showing the tag with the commit message is good.
In the context of CS21*3, it's also useful to show all tags in one place e.g., at the top of the commits view page (e.g., as a list of clickable links that auto-scrolls to the relevant commit). Perhaps here?
![image](https://user-images.githubusercontent.com/1673303/70874443-21066980-1fed-11ea-8874-f7259a7dd750.png)

Even better if we can find a way to show tags in the ramp charts page so that the viewer can see the tags without having to click at all. But we need to figure out a way to do that without taking a lot of space. Perhaps show it here, but only if the user ticks the `[ ] show tags` option?
![image](https://user-images.githubusercontent.com/1673303/70874404-eb618080-1fec-11ea-8b98-9ae925deeec8.png)
This can be a separate PR though.

**Comment by jamessspanggg** [comment]
> In the context of CS21*3, it's also useful to show all tags in one place e.g., at the top of the commits view page (e.g., as a list of clickable links that auto-scrolls to the relevant commit). 

Should the tags be in the same x-axis position as the corresponding commit in the chart? 

Also, to show the tags, should it be the in the same format (e.g. 🏷 v1.10, origin/release) from the left to the right of the ramp chart?

**Comment by damithc** [comment]
> Should the tags be in the same x-axis position as the corresponding commit in the chart? (if following this, some tags may be very closely together)

This will be hard to due to spacing issues e.g., when a commit has multiple tags. I guess no need.

> Also, to show the tags, should it be the in the same format (e.g. 🏷 v1.10, origin/release) from the left to the right of the ramp chart?

Yes. Perhaps the `repo/branch` can be omitted or shown on hover (to save space)?
