### ISSUE TITLE
RepoSense terminates abruptly when attempting to analyze filename of "\"

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#917]
When the file name is just `\` in MacOS (or other linux based OS), RepoSense attempts to analyze the file as `"\\"` due to [git diff munging of backslash character](https://git-scm.com/docs/git-diff/1.8.4#git-diff--z). 

This causes issues with the later part of the program when attempting to analyze the files and RepoSense terminates abruptly.

**Comment by myteo** [comment]
1. `FileInfoExtractor#DIFF_FILE_CHUNK_SEPARATOR` will fail to separate diff chunks properly as the file "\\" will be have the following header: `diff --git "a/\\" "b/\\"`.
2. `FileInfoExtractor#generateFileInfo` method, which reads the file line by line, will fail to open the file "\\" because file path has been munged.

**Comment by Tejas2805** [comment]
@jamessspanggg Does your PR that handles special characters solve this issue?

**Comment by jamessspanggg** [comment]
do u mean https://github.com/reposense/RepoSense/pull/1247? yes i believe the PR solves the issue.
