### ISSUE TITLE
Ramp chart: inconsistency in the length of contribution line

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#988]
When toggling between the `breakdown by filetype` checkbox, the length of the contribution line is inconsistent even though the LoC remains constant.

![Kapture 2020-01-14 at 23 24 12](https://user-images.githubusercontent.com/32864116/72356928-18589e80-3725-11ea-880c-eb1b89f3ad46.gif)
Link to reproduce:  https://jamessspanggg.github.io/OpenSourceContribution/

**Comment by damithc** [comment]
hmm... even the relative length between the bars seem to change. This is a non-trivial error.

**Comment by 0blivious** [comment]
The error is actually in the LOC counting of each file type due to the improper implementation of generated json file. Only the last entry is considered since the json file has multiple entries with same key name.

The wrong LOC of each file type at right.
![image](https://user-images.githubusercontent.com/39231750/72418356-9fedee00-37b5-11ea-9ccd-01ee05a9e425.png)
