### ISSUE TITLE
README: Briefly describe RepoSense features from the perspective of users

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#997]
Currently, we have provided a list of RepoSense's capabilities in the README.
It may be good to add a sentence describing these features from the user's perspective.

*An example*
RepoSense is a contribution analysis tool for Git repositories. **It can help educators keep track of work done in student projects, while developers can use it to generate portfolios displaying their open source contributions.** RepoSense generates a static HTML report including contribution information for each author in a repository. The features of the report include... (rest of README)

**Comment by damithc** [comment]
> while developers can use it to generate portfolios displaying their open source contributions

We don't have this feature yet. But we can mention that _team leads can use RepoSense to easily oversee the code written by developers under their charge_ ?

**Comment by anubh-v** [comment]
> >while developers can use it to generate portfolios displaying their open source contributions

> We don't have this feature yet.

Currently, developers can generate a *portfolio-of-sorts* by configuring `repo-config.csv` with all the repos they contribute to, and `author-config.csv` with only their own details. This would create a page showing their code contributions across projects. The report can be deployed on hosting platforms like GitHub pages.

I agree that this might not be a well polished solution for creating a portfolio *yet*, but it is still achievable with the current product. My opinion is that this use case should be mentioned in the README (or even user guide).

Credit: This use case was identified in discussion with @jamessspanggg yesterday

**Comment by damithc** [comment]
> I agree that this might not be a well polished solution for creating a portfolio _yet_, but it is still achievable with the current product. My opinion is that this use case should be mentioned in the README (or even user guide).

Let's keep that to ourselves for the time being as there are some fundamental incompatibilities. For example, RepoSense is optimized for monitoring a large number of relatively small repositories that are expected to be active around the same time. That description does not fit well for an individual portfolio e.g., an individual might contribute small PRs to several huge repos over a long period of time. If we were to support this use case well, we will have to do some major changes to the report format and even the way the report is generated, which I'm not keen to do at this time.

Also, it's best to focus on a smaller number of things rather than spread ourselves too thin.

**Comment by anubh-v** [comment]
> That description does not fit well for an individual portfolio e.g., an individual might contribute small PRs to several huge repos over a long period of time. If we were to support this use case well, we will have to do some major changes to the report format and even the way the report is generated

Thanks for the clarification. 
I see why we would not want to focus on the portfolio generation use case yet.
I will make a PR for this after discussing more with everyone else when we meet on 18th Jan.
